### PR TITLE
Various fixes for windows

### PR DESCRIPTION
**Pull request by gigabo**
This brings in https://github.com/lerna/lerna/pull/348 and https://github.com/lerna/lerna/pull/349 as a unit.

Need to squash/rebase merge to preserve authorship.

CC @motiz88

### CODE REVIEW

**Comment by gigabo** [comment]
@motiz88 Not sure what's up with the appveyor failure here... 😕

**Comment by motiz88** [comment]
@gigabo It seems like the failing tests are using un-normalized paths in their assertions, thus running into trailing backslash issues.

Compare:
- [test/BootstrapCommand.js#L61](https://github.com/gigabo/asini/blob/2e02e60c71698947362782b16737c78ce6a675bf/test/BootstrapCommand.js#L61)
- [test/BootstrapCommand.js#L164](https://github.com/gigabo/asini/blob/2e02e60c71698947362782b16737c78ce6a675bf/test/BootstrapCommand.js#L164)

**Comment by gigabo** [comment]
Oh!  Those must be tests that we've added since we diverged from Lerna... 😖 

Thanks for looking at it @motiz88!

**Comment by gigabo** [comment]
Okay, got it all worked out.  Thanks again @motiz88!

**Pull request merged**
