### PR TITLE
Refactor BootstrapMixin from a mixin into a utility

### PR DESCRIPTION
**Pull request by sresant**

### CODE REVIEW

**Comment by gigabo** [comment]
@sresant Thanks for this!

Looks like just a couple of linter errors:

image

**Comment by evocateur** [comment]
Always a good idea to `npm run lint` before pushing.

**Comment by gigabo** [comment]
Yeah, I try to remember to just do a full `npm run ci`.

... then it's just Windows that winds up biting me. :feelsgood:

**Comment by evocateur** [comment]
15f51ab looks great, btw. @gigabo Can we just cherry-pick/squash this into #46 ?

**Comment by sresant** [comment]
Yea I ran npm test, just totally forgot about the linter. I'll just do `npm run ci` next time

**Comment by gigabo** [comment]
My commit history on #46 is a mess.  Maybe nicer to _squash_ that and then rebase this so we just get a single commit on master from each PR?

**Comment by evocateur** [comment]
Sure, we can squash this one or that one. I like squash merging.

**Comment by rygine** [comment]
the unit tests here seem unnecessary. not sure if we should move some of the functionality testing out of other tests into here, or simply add additional tests for each utility function. hmmm...

**Comment by evocateur** [comment]
@rygine Yeah, the current unit tests for `BootstrapUtilities` are rather anemic, and should properly take over responsibility for the tests of the extracted methods currently found in the `BootstrapCommand` tests. This allows the `AddCommand` tests to assert that a given utility method was called, and boom less duplicated, more readable code.

That being said, there is a lot of room for better factoring in general with the current tests, and the minimal "smoke test" pattern of merely asserting a given property exists is on the top of my list of patterns to nuke.

**Comment by gigabo** [comment]
Alright, looks like this is good to go.  Thanks @sresant!

**Pull request merged**
