### PR TITLE
Add yarn support

### PR DESCRIPTION
**Pull request by doug-wade**
Adds the yarn.lock files per https://yarnpkg.com/blog/2016/11/24/lockfiles-for-all
I also dropped node 5 support, since its [no longer supported](https://github.com/nodejs/LTS) but that maybe should go in another pr?

### CODE REVIEW

**Comment by gigabo** [comment]
> Adds the yarn.lock files

Nice!  Should probably hold off on this until we [get bootstrap working with yarn](https://github.com/asini/asini/issues/56).  Since Asini is an Asini repo deps should be installed with `asini bootstrap`.

> I also dropped node 5 support, since its no longer supported but that maybe should go in another pr?

Oh, nice didn't know about that!  Yeah, that deserves a dedicated PR that we can merge right away.

**Comment by doug-wade** [comment]
> Since Asini is an Asini repo deps should be installed with asini bootstrap

I think I'm misunderstanding something here.  I thought the idea was to check in lockfiles for dependencies so that when I install asini using yarn in react-server, I get the set of dependencies specified in asini and asini-changelog's yarn.lock.  That is to say, I thought I was checking the `yarn.lock` for users who use `yarn` to install `asini`, not for people who are developing `asini` (since, as you note, we don't use `yarn` to develop on `asini`).

**Review by gigabo — APPROVED** [review]
Oh!!!  I totally misunderstood.  😅 

Thanks @doug-wade, good improvement!

**Comment by evocateur** [comment]
From the linked yarn blog post, it explicitly states that lockfiles found in dependencies are ignored. Why would a user installing Asini with yarn need these lockfiles?

> When you publish a package that contains a yarn.lock, any user of that library will not be affected by it. When you install dependencies in your application or library, only your own yarn.lock file is respected. Lockfiles within your dependencies will be ignored.

**Comment by gigabo** [comment]
Oh.  Thanks @evocateur for actually reading the blog post. 😆 

So... maybe this _is_ only relevant once Asini has pluggable npm clients and can use `yarn` to bootstrap itself?

**Comment by evocateur** [comment]
@gigabo Yes, that's my understanding.

**Pull request closed without merging**
