### PR TITLE
Get logify* methods working again

### PR DESCRIPTION
**Pull request by gigabo**
The `@logger.logify*` decorators weren't getting wired up right.

Maybe due to updates in babel's decorator handling?  Not sure.

Changes necessary:
- Assign to `descriptor.value` instead of just returning function
- Reference the logger instance directly instead of as `this`

According to [wycats](https://github.com/wycats/javascript-decorators#detailed-design) a decorator is "an expression that evaluates to a function".  Guess it loses its context binding in the process?

Anyway, this gets it working.

I also changed the log level to `silly`, and removed the (now obsolete) extra `verbose` argument.

### CODE REVIEW

**Comment by gigabo** [comment]
Whoa... this is causing a core dump on node `6.6.0` in travis!

```
<--- Last few GCs --->
   10333 ms: Mark-sweep 1058.3 (1222.9) -> 916.7 (1091.6) MB, 24.5 / 0.2 ms (+ 60.8 ms in 3470 steps since start of marking, biggest step 2.4 ms) [allocation failure] [GC in old space requested].
   10371 ms: Mark-sweep 916.7 (1091.6) -> 914.9 (1092.6) MB, 38.1 / 0.0 ms [allocation failure] [GC in old space requested].
   10419 ms: Mark-sweep 914.9 (1092.6) -> 911.5 (1048.6) MB, 48.4 / 0.0 ms [last resort gc].
   10453 ms: Mark-sweep 911.5 (1048.6) -> 911.2 (1041.6) MB, 33.8 / 0.0 ms [last resort gc].
<--- JS stacktrace --->
==== JS stack trace =========================================
Security context: 0x1c6b01cfb51 <JS Object>
    1: replace [native string.js:~132] [pc=0x1e33fbc923e1] (this=0x509eaf0c651 <Very long string[243714580]>,O=0x41aeb97e751 <String[30]: /home/travis/build/asini/asini>,P=0x1c6b0104a59 <String[1]: .>)
    2: _formatValue(aka _formatValue) [/home/travis/build/asini/asini/src/logger.js:~151] [pc=0x1e33fbd27fc8] (this=0x1c6b0104381 <undefined>,arg=0x86f76604201 <Very long string[147914059]>)
    3...
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [/home/travis/.nvm/versions/node/v6.6.0/bin/node]
 2: 0x10a3b3c [/home/travis/.nvm/versions/node/v6.6.0/bin/node]
 3: v8::Utils::ReportApiFailure(char const*, char const*) [/home/travis/.nvm/versions/node/v6.6.0/bin/node]
 4: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [/home/travis/.nvm/versions/node/v6.6.0/bin/node]
 5: v8::internal::Factory::NewRawTwoByteString(int, v8::internal::PretenureFlag) [/home/travis/.nvm/versions/node/v6.6.0/bin/node]
 6: v8::internal::String::SlowFlatten(v8::internal::Handle<v8::internal::ConsString>, v8::internal::PretenureFlag) [/home/travis/.nvm/versions/node/v6.6.0/bin/node]
 7: v8::internal::StringMatch(v8::internal::Isolate*, v8::internal::Handle<v8::internal::String>, v8::internal::Handle<v8::internal::String>, int) [/home/travis/.nvm/versions/node/v6.6.0/bin/node]
 8: v8::internal::Runtime_StringIndexOf(int, v8::internal::Object**, v8::internal::Isolate*) [/home/travis/.nvm/versions/node/v6.6.0/bin/node]
 9: 0x1e33fac092a7
Aborted (core dumped)
```

**Comment by gigabo** [comment]
Tracked it down.  Will be fixed by rebasing onto #7 once that lands.

All logger output is currently captured during all tests.  Just a leak.

**Review by rygine — APPROVED** [review]
LGTM

**Comment by gigabo** [comment]
Thanks @rygine!

**Pull request merged**
