### PR TITLE
Change bootstrap command to not install peerDependencies (#318)

### PR DESCRIPTION
**Pull request by gigabo**
As of npm@3, peerDependencies were no longer installed with
`npm install`. The bootstrap command should conform to this behaviour.

### CODE REVIEW

**Comment by gigabo** [comment]
Born from https://github.com/lerna/lerna/pull/318.  Need to merge this non-squash to preserve @loklaan's authorship.

**Review by rygine — APPROVED** [review]
LGTM

**Comment by gigabo** [comment]
Thanks @loklaan!

**Comment by loklaan** [comment]
No worries mate.

**Pull request merged**
