### PR TITLE
Run pre/post install scripts during bootstrap

### PR DESCRIPTION
**Pull request by gigabo**
Born from https://github.com/lerna/lerna/pull/358.

Need to merge non-squash to preserve authorship.

CC @seansfkelley

This is an awesome improvement.  Lays the groundwork for other easy topo-ordered operations.

### CODE REVIEW

**Comment by gigabo** [comment]
I'd like to get this merged in before getting too far into #14, since they're likely to conflict.

This looks great to me.  @rygine?

**Review by rygine — APPROVED** [review]
LGTM! 🎉

**Comment by gigabo** [comment]
Thanks @seansfkelley!

**Comment by gigabo** [comment]
This landed in `asini@1.0.0`.

**Pull request merged**
